services:
  app:
    build: .
    container_name: 1Space
    ports:
      - "8080:8080"
    environment:
      # Пусть приложение найдёт файл с ключом
      - GOOGLE_APPLICATION_CREDENTIALS=/main/firebase.json
    volumes:
      # Привяжем ваш локальный файл с JSON-ключом
      - ./firebase.json:/main/firebase.json:ro
